<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Teracura.TestingWebApp.Interfaces</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NizamDesk.API\NizamDesk.API.csproj" />
      <ProjectReference Include="..\NizamDesk.Entities\NizamDesk.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
